"""initial schema: missions, image_sequences, images

Revision ID: 21da1a67eaa3
Revises: 
Create Date: 2026-09-13 12:00:49.223824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21da1a67eaa3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_name', sa.String(length=100), nullable=False),
    sa.Column('instrument_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_name', 'instrument_name', name='uq_mission_instrument')
    )
    op.create_table('image_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'READY', 'PROCESSING', 'PROCESSED', 'FAILED')", name='ck_sequence_status'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_sequences_mission_id'), 'image_sequences', ['mission_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('observation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instrument', sa.String(length=50), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('ingestion_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ingestion_status IN ('complete', 'failed')", name='ck_image_ingestion_status'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['image_sequences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_identifier')
    )
    op.create_index(op.f('ix_images_mission_id'), 'images', ['mission_id'], unique=False)
    op.create_index(op.f('ix_images_observation_time'), 'images', ['observation_time'], unique=False)
    op.create_index(op.f('ix_images_sequence_id'), 'images', ['sequence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_sequence_id'), table_name='images')
    op.drop_index(op.f('ix_images_observation_time'), table_name='images')
    op.drop_index(op.f('ix_images_mission_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_image_sequences_mission_id'), table_name='image_sequences')
    op.drop_table('image_sequences')
    op.drop_table('missions')
    # ### end Alembic commands ###
