"""add instrument to image_sequences

Revision ID: eb000fe4d0b1
Revises: 21da1a67eaa3
Create Date: 2026-09-13 12:15:04.669407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb000fe4d0b1'
down_revision: Union[str, Sequence[str], None] = '21da1a67eaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    NOT NULL without a server default is safe here: image_sequences is empty
    at this revision (sequence grouping ships in the same session).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_sequences', sa.Column('instrument', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_image_sequences_instrument'), 'image_sequences', ['instrument'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_sequences_instrument'), table_name='image_sequences')
    op.drop_column('image_sequences', 'instrument')
    # ### end Alembic commands ###
